---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
       - htop
       - vim
       - curl
       - python3-pip
  - name: install spotify
    community.general.snap:
      name:
        - spotify



