---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
       - git-all
       - htop
       - vim
       - curl
       - python3-pip
       - python3-venv
       - terminator
       - geany
       - stacer

  - name: install snap apps
    community.general.snap:
      name:
        - spotify
        - postman
        - telegram-desktop
        - pomatez
        - gimp
        - vlc

  - name: install kubectl
    community.general.snap:
      name: kubectl
      classic: true

  - name: install pycharm-professional
    community.general.snap:
      name: pycharm-professional
      classic: true

  - name: install pipx
    ansible.builtin.pip:
      name: pipx

  - name: execute ensurepip
    ansible.builtin.command: pipx ensurepath --force
    become: yes
    become_user: avallbona

#   - name: install black with pipx
#     community.general.pipx:
#       name: black
#
#   - name: install isort with pipx
#     community.general.pipx:
#       name: isort
#
#   - name: install pre-commit with pipx
#     community.general.pipx:
#       name: pre-commit

  # docker
  - name: install packages necessary for docker
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      update_cache: yes

  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable

  - name: install docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes

  - name: add user permissions
    shell: "usermod -aG docker {{ ansible_env.SUDO_USER }}"

  # end docker