---
- hosts: localhost
  connection: local
  become: true
  collections:
    - community.general

  tasks:
  - name: install packages
    package:
      name: 
       - git-all
       - htop
       - vim
       - curl
       - python3-pip
       - terminator
       - geany
       - stacer

  - name: install snap apps
    community.general.snap:
      name:
        - spotify
        - postman
        - telegram-desktop
        - pomatez
        - gimp
        - vlc

  - name: install kubectl
    community.general.snap:
      name: kubectl
      classic: true

  - name: install pycharm-professional
    community.general.snap:
      name: pycharm-professional
      classic: true

  - name: install pipx
    ansible.builtin.pip:
      name: pipx

  - name: install black with pipx
    community.general.pipx:
      name: black

  - name: install isort with pipx
    community.general.pipx:
      name: isort

  - name: install pre-commit with pipx
    community.general.pipx:
      name: pre-commit


