---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
#        - git-all
       - htop
       - vim
       - curl
       - python3-pip
       - terminator
       - geany
       - stacer

  - name: install snap apps
    community.general.snap:
      name:
        - spotify
        - postman
        - telegram-desktop
        - pomatez
        - gimp
        - vlc
#
#   - name: install kubectl
#     community.general.snap:
#       name: kubectl
#       classic: true
#
  - name: install pycharm-professional
    community.general.snap:
      name: pycharm-professional
      classic: true
#
#   - name: install pipx
#     ansible.builtin.pip:
#       name: pipx
#
#   - name: install pipx apps
#     community.general.pipx:
#       name:
#         - black
#         - isort
#         - pre-commit


